<?php
declare(strict_types=1);
require __DIR__ . '/_bootstrap.php';
$site=setting('site',[]); $projects=public_projects(true); $categories=categories();
$initialCategory=safe_slug((string)($_GET['kategori'] ?? 'all')) ?: 'all';
$initialStatus=safe_slug((string)($_GET['durum'] ?? 'all')) ?: 'all';
$statuses=[]; foreach($projects as $p){$statuses[$p['status']]=$p['status_label'];}
?>
<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="Ahmet Çetin'in seçilmiş, düzenlenmiş ve yayımlanmış proje hikâyeleri. Ham Atölye kayıtları ayrı bir Atölye Günlüğü kavramıdır."><meta name="theme-color" content="#eee5d4"><title>Hikâyeler | #FikrimVar</title><link rel="canonical" href="https://www.acetin.com.tr/hikayeler.php"><?= public_theme_boot_script() ?><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,400;9..144,600&family=IBM+Plex+Mono:wght@400;500;600&family=Inter:wght@400;500;600&display=swap" rel="stylesheet"><link rel="stylesheet" href="<?= e(asset_url('assets/css/style.css')) ?>"><link rel="stylesheet" href="<?= e(asset_url('assets/css/stories.css')) ?>"><script src="<?= e(asset_url('assets/js/app.js')) ?>" defer></script></head>
<body class="stories-page"><a class="skip-link" href="#stories-main">İçeriğe geç</a><header class="inner-header"><div class="shell inner-header-row"><a class="brand" href="index.php"><span class="brand-name">AHMET ÇETİN</span><span class="brand-mark">#FikrimVar</span></a><nav><a href="index.php">Ana sayfa</a><?= public_theme_toggle() ?></nav></div></header>
<main id="stories-main"><section class="stories-hero-v6"><div class="shell stories-hero-v6-grid"><div data-reveal><p class="eyebrow">DÜZENLENMİŞ HİKÂYELER · <?= count($projects) ?> HİKÂYE</p><h1>Bütün<br> <em>hikâyeler.</em></h1></div><div data-reveal><p>Bu sayfa ham Atölye kayıtlarının akışı değil. Burada projelerden seçilip okunabilir bir anlatıya dönüştürülmüş hikâyeler duruyor.</p><p>Bir hikâyeyi açtığında yalnızca sonucu değil; neden başladığını, nerede zorlandığını, neyin değiştiğini ve bugün nerede durduğunu görürsün.</p></div></div></section>
<section class="stories-browser" data-story-index data-initial-category="<?= e($initialCategory) ?>" data-initial-status="<?= e($initialStatus) ?>"><div class="shell"><div class="story-filter-bar"><div class="category-filter" role="group"><button class="<?= $initialCategory==='all'?'is-active':'' ?>" type="button" data-story-category="all" aria-pressed="<?= $initialCategory==='all'?'true':'false' ?>">Tümü</button><?php foreach($categories as $c): ?><button class="<?= $initialCategory===$c['slug']?'is-active':'' ?>" type="button" data-story-category="<?= e($c['slug']) ?>" aria-pressed="<?= $initialCategory===$c['slug']?'true':'false' ?>"><?= e($c['title']) ?></button><?php endforeach; ?></div><div class="story-filter-tools"><label><span>Durum</span><select data-story-status><option value="all">Tüm durumlar</option><?php foreach($statuses as $k=>$v): ?><option value="<?= e($k) ?>" <?= $initialStatus===$k?'selected':'' ?>><?= e($v) ?></option><?php endforeach; ?></select></label><label><span>Ara</span><input type="search" placeholder="Başlık, araç veya soru" data-story-search autocomplete="off"></label></div></div><div class="story-results-bar"><p><strong data-story-count><?= count($projects) ?></strong> hikâye</p><p>Atölye Günlüğü ayrı bir ham kayıt akışı olarak hazırlanacak; bu sayfa düzenlenmiş hikâyeleri listeler.</p></div>
<div class="stories-mosaic"><?php foreach(array_values($projects) as $i=>$p): $shape=['wide','tall','compact','offset'][$i%4]; $search=implode(' ',[$p['title'],$p['question'],$p['summary'],$p['project_title'] ?? '',$p['category_label'],$p['status_label'],implode(' ',$p['tags'] ?? [])]); ?><article class="mosaic-story mosaic-story--<?= e($shape) ?>" data-story-card data-category="<?= e($p['category']) ?>" data-status="<?= e($p['status']) ?>" data-search="<?= e($search) ?>"><a href="<?= e(story_url($p)) ?>"><?php if($p['cover']!==''): ?><figure><img src="<?= e($p['cover']) ?>" alt="<?= e($p['project_title'] ?: $p['title']) ?>" loading="lazy"></figure><?php endif; ?><div class="mosaic-story-copy"><p><?= e($p['category_label']) ?> · <?= e($p['status_label']) ?></p><em class="story-project-id"><?= e($p['project_title'] ?: $p['title']) ?><?php if(!empty($p['type_label'])): ?> · <?= e($p['type_label']) ?><?php endif; ?></em><h2><?= e($p['question'] ?: $p['title']) ?></h2><span><?= e($p['summary']) ?></span><small><?= e($p['type_label']) ?> <?= icon('arrow') ?></small></div></a></article><?php endforeach; ?></div><p class="story-no-results" data-story-empty hidden>Bu filtrelerle eşleşen bir hikâye bulunamadı.</p></div></section></main><footer class="site-footer"><div class="shell footer-inner"><p>© <?= e((string)($site['year'] ?? date('Y'))) ?> Ahmet Çetin · #FikrimVar</p><a href="index.php">Ana sayfaya dön <?= icon('arrow') ?></a></div></footer></body></html>
