<?php
declare(strict_types=1);
require __DIR__ . '/_bootstrap.php'; admin_require_login();
$id=(int)($_GET['id'] ?? $_POST['id'] ?? 0); $project=null;
$st=db()->prepare("SELECT p.*,c.title category_title,m.relative_path cover_path,s.id story_id,s.status story_status,s.visibility story_visibility
 FROM projects p LEFT JOIN categories c ON c.id=p.category_id LEFT JOIN media m ON m.id=p.cover_media_id LEFT JOIN stories s ON s.project_id=p.id AND s.deleted_at IS NULL WHERE p.id=?"); $st->execute([$id]); $project=$st->fetch();
if(!$project){http_response_code(404);exit('Proje bulunamadı.');}
$cats=categories(false); $media=project_media_admin($id); $updates=project_updates($id,false); $links=owner_links('project',$id); $error='';
if(is_post()){
    verify_csrf(); $action=(string)($_POST['action'] ?? 'save');
    try{
        if($action==='delete'){soft_delete_project($id);admin_audit('trash','project',$id);flash('success','Proje çöp kutusuna taşındı.');redirect('index.php');}
        if($action==='restore'){db()->prepare('UPDATE projects SET deleted_at=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=?')->execute([$id]);flash('success','Proje geri yüklendi.');redirect('project-edit.php?id='.$id);}
        if($action==='permanent_delete'){
            $slug=$project['slug']; db()->prepare('DELETE FROM projects WHERE id=?')->execute([$id]); admin_audit('permanent_delete','project',$id,$slug); flash('success','Proje kalıcı silindi. Medya dosyaları diskte güvenlik için bırakıldı.'); redirect('index.php?filter=trash');
        }
        db()->beginTransaction();
        $title=trim(old('title')); $slug=safe_slug(old('slug')); if($title===''||$slug==='') throw new RuntimeException('Başlık ve slug gerekli.');
        $st=db()->prepare("UPDATE projects SET slug=?,title=?,question=?,summary=?,category_id=?,status=?,status_label=?,type_label=?,visibility=?,workshop_status=?,workshop_question=?,closing_state=?,closing_note=?,started_at=?,ended_at=?,show_on_home=?,show_in_archive=?,show_in_widget=?,is_pinned=?,home_section=?,sort_order=?,updated_at=CURRENT_TIMESTAMP WHERE id=?");
        $st->execute([$slug,$title,trim(old('question')),trim(old('summary')),(int)($_POST['category_id'] ?? 0)?:null,(string)($_POST['status'] ?? 'draft'),trim(old('status_label')) ?: 'Kayıt',trim(old('type_label')) ?: 'Proje',(string)($_POST['visibility'] ?? 'private'),(string)($_POST['workshop_status'] ?? 'none'),trim(old('workshop_question')),old('closing_state')?:null,trim(old('closing_note')),old('started_at')?:null,old('ended_at')?:null,checkbox('show_on_home'),checkbox('show_in_archive'),checkbox('show_in_widget'),checkbox('is_pinned'),(string)($_POST['home_section'] ?? 'none'),(float)($_POST['sort_order'] ?? 999),$id]);
        if(checkbox('is_pinned')) db()->prepare('UPDATE projects SET is_pinned=0 WHERE id<>?')->execute([$id]);
        // tags
        db()->prepare('DELETE FROM project_tags WHERE project_id=?')->execute([$id]);
        foreach(array_filter(array_map('trim',explode(',',old('tags')))) as $tag){$ts=safe_slug($tag) ?: substr(sha1($tag),0,8);db()->prepare('INSERT OR IGNORE INTO tags(name,slug) VALUES (?,?)')->execute([$tag,$ts]);$tid=(int)db()->query("SELECT id FROM tags WHERE name=".db()->quote($tag))->fetchColumn();db()->prepare('INSERT OR IGNORE INTO project_tags(project_id,tag_id) VALUES (?,?)')->execute([$id,$tid]);}
        // cover existing/new
        $new=save_uploaded_files($id,$slug,'cover_upload'); $coverId=$new[0] ?? (int)($_POST['cover_media_id'] ?? 0); if($coverId) db()->prepare('UPDATE projects SET cover_media_id=? WHERE id=?')->execute([$coverId,$id]);
        // project links replace
        db()->prepare("DELETE FROM links WHERE owner_type='project' AND owner_id=?")->execute([$id]);
        foreach($_POST['links'] ?? [] as $i=>$l){$url=safe_external_url((string)($l['url']??''));if($url==='')continue;db()->prepare("INSERT INTO links(owner_type,owner_id,link_type,title,url,sort_order) VALUES ('project',?,?,?,?,?)")->execute([$id,trim((string)($l['type']??'external')),trim((string)($l['title']??'Bağlantı')),$url,(int)$i]);}
        db()->commit(); admin_audit('update','project',$id,$title); flash('success','Proje kaydedildi.'); redirect('project-edit.php?id='.$id);
    }catch(Throwable $e){if(db()->inTransaction())db()->rollBack();$error=$e->getMessage();}
}
$tags=implode(', ',project_tags($id)); admin_head('Projeyi yönet'); ?>
<div class="page-head"><div><p class="eyebrow">PROJE #<?= $id ?></p><h1><?= e($project['title']) ?></h1><p>Yayın, görünürlük ve sıra birbirinden bağımsızdır. İçeriği silmeden gizleyebilirsin.</p></div><div class="form-actions"><a class="button secondary" href="update-new.php?project_id=<?= $id ?>">+ Atölye kaydı</a><a class="button secondary" href="story-builder.php?project_id=<?= $id ?>">Atölyeden hikâye</a><?php if($project['story_id']): ?><a class="button secondary" href="story-edit.php?project_id=<?= $id ?>">Hikâyeyi düzenle</a><?php endif; ?></div></div><?php if($error): ?><div class="flash flash-error"><?= e($error) ?></div><?php endif; ?>
<form method="post" enctype="multipart/form-data"><input type="hidden" name="id" value="<?= $id ?>"><?= csrf_field() ?><div class="grid grid-2"><section class="panel"><h2>Kimlik ve anlatı</h2><div class="form-grid"><div class="field"><label>Başlık</label><input name="title" value="<?= e($project['title']) ?>" required></div><div class="field"><label>Slug</label><input name="slug" value="<?= e($project['slug']) ?>" required></div><div class="field full"><label>Merak sorusu</label><input name="question" value="<?= e($project['question']) ?>"></div><div class="field full"><label>Özet</label><textarea name="summary"><?= e($project['summary']) ?></textarea></div><div class="field"><label>Kategori</label><select name="category_id"><option value="">Seçin</option><?php foreach($cats as $c): ?><option value="<?= (int)$c['id'] ?>" <?= (int)$project['category_id']===(int)$c['id']?'selected':'' ?>><?= e($c['title']) ?></option><?php endforeach; ?></select></div><div class="field"><label>Etiketler</label><input name="tags" value="<?= e($tags) ?>" placeholder="Python, Yapay zekâ, Krita"></div><div class="field"><label>Durum kodu</label><select name="status"><?php foreach(['fikir','suruyor','calisiyor','denendi','tamamlandi','yarim','not','arsiv'] as $v): ?><option value="<?= $v ?>" <?= $project['status']===$v?'selected':'' ?>><?= $v ?></option><?php endforeach; ?></select></div><div class="field"><label>Görünen durum</label><input name="status_label" value="<?= e($project['status_label']) ?>"></div><div class="field"><label>İçerik türü</label><input name="type_label" value="<?= e($project['type_label']) ?>"></div></div></section>
<aside class="panel"><h2>Yayın ve görünürlük</h2><div class="field"><label>Görünürlük</label><select name="visibility"><option value="private" <?= $project['visibility']==='private'?'selected':'' ?>>Gizli</option><option value="unlisted" <?= $project['visibility']==='unlisted'?'selected':'' ?>>Bağlantıya sahip olanlar</option><option value="public" <?= $project['visibility']==='public'?'selected':'' ?>>Herkese açık</option></select></div><div class="field"><label>Ana sayfa alanı</label><select name="home_section"><option value="none" <?= $project['home_section']==='none'?'selected':'' ?>>Gösterme</option><option value="focus" <?= $project['home_section']==='focus'?'selected':'' ?>>Büyük hikâye</option><option value="trace" <?= $project['home_section']==='trace'?'selected':'' ?>>Masanın diğer tarafı</option></select></div><div class="field"><label>Sıra</label><input type="number" step="0.1" name="sort_order" value="<?= e((string)$project['sort_order']) ?>"></div><div class="check-row"><label class="check"><input type="checkbox" name="show_on_home" <?= $project['show_on_home']?'checked':'' ?>> Ana sayfa</label><label class="check"><input type="checkbox" name="show_in_archive" <?= $project['show_in_archive']?'checked':'' ?>> Arşiv</label><label class="check"><input type="checkbox" name="show_in_widget" <?= $project['show_in_widget']?'checked':'' ?>> Atölye penceresi</label><label class="check"><input type="checkbox" name="is_pinned" <?= $project['is_pinned']?'checked':'' ?>> Sabitle</label></div></aside>
<section class="panel"><h2>Atölye yaşam döngüsü</h2><div class="form-grid"><div class="field"><label>Atölye durumu</label><select name="workshop_status"><option value="none" <?= $project['workshop_status']==='none'?'selected':'' ?>>Yok</option><option value="open" <?= $project['workshop_status']==='open'?'selected':'' ?>>Açık</option><option value="paused" <?= $project['workshop_status']==='paused'?'selected':'' ?>>Beklemede</option><option value="closed" <?= $project['workshop_status']==='closed'?'selected':'' ?>>Kapandı</option></select></div><div class="field"><label>Atölye sorusu</label><input name="workshop_question" value="<?= e($project['workshop_question']) ?>"></div><div class="field"><label>Başlangıç tarihi</label><input type="date" name="started_at" value="<?= e((string)$project['started_at']) ?>"></div><div class="field"><label>Bitiş tarihi</label><input type="date" name="ended_at" value="<?= e((string)$project['ended_at']) ?>"></div><div class="field"><label>Kapanış kararı</label><select name="closing_state"><option value="">Seçin</option><?php foreach(['Bu hâliyle bitti','Yarım bıraktım','Beklemeye aldım','Başka projeye dönüştü'] as $v): ?><option <?= $project['closing_state']===$v?'selected':'' ?>><?= e($v) ?></option><?php endforeach; ?></select></div><div class="field full"><label>Kapanış notu</label><textarea name="closing_note"><?= e($project['closing_note']) ?></textarea></div></div></section>
<aside class="panel"><h2>Kapak ve medya</h2><?php if($project['cover_path']): ?><img style="width:100%;max-height:220px;object-fit:cover;border-radius:8px" src="../public/<?= e($project['cover_path']) ?>" alt=""><?php endif; ?><div class="field"><label>Yeni kapak yükle</label><input type="file" name="cover_upload[]" accept="image/jpeg,image/png,image/webp,image/gif"></div><div class="field"><label>Mevcut medyadan kapak</label><select name="cover_media_id"><option value="">Değiştirme</option><?php foreach($media as $m): if($m['media_type']!=='image')continue; ?><option value="<?= (int)$m['id'] ?>" <?= (int)$project['cover_media_id']===(int)$m['id']?'selected':'' ?>><?= e($m['original_name']) ?></option><?php endforeach; ?></select></div><a class="button secondary" href="media.php?project_id=<?= $id ?>">Medya kütüphanesi</a></aside>
<section class="panel"><h2>Proje bağlantıları</h2><div id="project-links" class="repeat-list"><?php foreach($links as $i=>$l): ?><div class="repeat-row"><select name="links[<?= $i ?>][type]"><?php foreach(['website','youtube','instagram','github','download','external'] as $t): ?><option <?= $l['link_type']===$t?'selected':'' ?>><?= $t ?></option><?php endforeach; ?></select><input name="links[<?= $i ?>][title]" value="<?= e($l['title']) ?>" placeholder="Başlık"><input name="links[<?= $i ?>][url]" value="<?= e($l['url']) ?>" placeholder="https://"><button class="danger" type="button" data-repeat-remove>Sil</button></div><?php endforeach; ?></div><button class="secondary" type="button" data-repeat-add="#project-links" data-template="#link-template">+ Bağlantı ekle</button></section>
<aside class="panel"><h2>Kayıtlar</h2><p><?= count($updates) ?> Atölye kaydı var.</p><a class="button secondary" href="update-new.php?project_id=<?= $id ?>">Yeni kayıt</a><?php if($updates): ?><div class="list" style="margin-top:14px"><?php foreach(array_slice(array_reverse($updates),0,5) as $u): ?><a class="list-row" href="update-edit.php?id=<?= (int)$u['id'] ?>"><span><?= e($u['date_label']) ?></span><strong><?= e($u['title']) ?></strong><small><?= $u['status']==='published'?'Yayında':'Taslak' ?></small></a><?php endforeach; ?></div><?php endif; ?></aside></div>
<div class="form-actions"><button class="accent" type="submit" name="action" value="save">Projeyi kaydet</button><a class="button secondary" href="index.php">Listeye dön</a><?php if(!$project['deleted_at']): ?><button class="danger" type="submit" name="action" value="delete" data-confirm="Proje çöp kutusuna taşınsın mı?">Çöp kutusuna taşı</button><?php else: ?><button type="submit" name="action" value="restore">Geri yükle</button><button class="danger" type="submit" name="action" value="permanent_delete" data-confirm="Bu işlem geri alınamaz. Kalıcı silinsin mi?">Kalıcı sil</button><?php endif; ?></div></form>
<template id="link-template"><div class="repeat-row"><select name="links[__INDEX__][type]"><option>website</option><option>youtube</option><option>instagram</option><option>github</option><option>download</option><option>external</option></select><input name="links[__INDEX__][title]" placeholder="Başlık"><input name="links[__INDEX__][url]" placeholder="https://"><button class="danger" type="button" data-repeat-remove>Sil</button></div></template>
<?php admin_foot(); ?>
