<?php
declare(strict_types=1);

function render_update_form(array $project,array $update=[],array $attached=[],array $links=[]): void
{
    $isEdit=!empty($update['id']); $media=project_media_admin((int)$project['id']);
    $v=fn(string $k,string $d='')=>e((string)($update[$k] ?? $d));
    ?>
    <div class="grid grid-2">
    <section class="panel"><h2>Calisma kaydi</h2><div class="form-grid"><div class="field"><label>Calismanin tarihi</label><input type="date" name="work_date" value="<?= $v('work_date',date('Y-m-d')) ?>"></div><div class="field"><label>Gorunen tarih / etiket</label><input name="display_label" value="<?= $v('display_label') ?>" placeholder="Bos ise tarihten olusur"></div><div class="field full"><label>Baslik</label><input name="title" value="<?= $v('title') ?>" required></div><div class="field full"><label>Kisa ozet</label><textarea name="summary"><?= $v('summary') ?></textarea></div><div class="field full"><label>Ne denedim?</label><textarea name="tried"><?= $v('tried') ?></textarea></div><div class="field full"><label>Ne calismadi?</label><textarea name="failed"><?= $v('failed') ?></textarea></div><div class="field full"><label>Hangi karari verdim?</label><textarea name="decision"><?= $v('decision') ?></textarea></div><div class="field full"><label>Sirada ne var?</label><textarea name="next_step"><?= $v('next_step') ?></textarea></div><div class="field"><label>Faz / donem</label><input name="phase" value="<?= $v('phase','Genel') ?>" placeholder="Baslangic, Denemeler, Yon degisikligi"></div><div class="field"><label>Slug</label><input name="slug" value="<?= $v('slug') ?>" placeholder="Bos ise basliktan olusur"></div></div></section>
    <aside class="panel"><h2>Atolye kaydi gorunurlugu</h2><div class="field"><label>Durum</label><select name="status"><option value="draft" <?= ($update['status']??'draft')==='draft'?'selected':'' ?>>Taslak</option><option value="published" <?= ($update['status']??'')==='published'?'selected':'' ?>>Yayimla</option></select></div><div class="field"><label>Gorunurluk</label><select name="visibility"><option value="private" <?= ($update['visibility']??'public')==='private'?'selected':'' ?>>Gizli</option><option value="unlisted" <?= ($update['visibility']??'')==='unlisted'?'selected':'' ?>>Baglantiya sahip olanlar</option><option value="public" <?= ($update['visibility']??'public')==='public'?'selected':'' ?>>Herkese acik</option></select></div><div class="field"><label>Proje ici calisma sirasi</label><input type="number" step="0.1" name="sort_order" value="<?= $v('sort_order') ?>" placeholder="Bos ise sistem sonraki sirayi verir"></div><div class="check-row"><label class="check"><input type="checkbox" name="is_milestone" <?= !empty($update['is_milestone'])?'checked':'' ?>> Donum noktasi</label><label class="check"><input type="checkbox" name="show_in_recent" <?= !isset($update['show_in_recent'])||$update['show_in_recent']?'checked':'' ?>> Son hareketlerde goster</label></div><p class="help">Bu yayin sirasi degil; yalnizca bu projenin Atolye kayitlari icindeki akisi belirler. Bos birakirsan sistem onceki kaydin ardindan uygun sirayi verir.</p><p class="help">Donum noktasi, her kayit degil; hikayeye tasinmaya deger yon degistiren veya ozetleyen kayittir.</p></aside>
    <section class="panel"><h2>Yeni medya yukle</h2><div class="field"><label>Gorsel, video, ses veya PDF</label><input type="file" name="media_files[]" multiple accept="image/jpeg,image/png,image/webp,image/gif,video/mp4,video/webm,audio/mpeg,audio/wav,audio/ogg,application/pdf"><small>Bir kayda birden fazla dosya eklenebilir. Buyuk videolarda YouTube baglantisi daha hafif olur.</small></div></section>
    <aside class="panel"><h2>Mevcut medyadan sec</h2><div class="media-grid"><?php foreach($media as $m): ?><label class="media-card"><input type="checkbox" name="existing_media_ids[]" value="<?= (int)$m['id'] ?>"><?php if($m['media_type']==='image'): ?><img src="../<?= e($m['relative_path']) ?>" alt=""><?php else: ?><div style="height:120px;display:grid;place-items:center;background:#090d11"><?= e(strtoupper($m['media_type'])) ?></div><?php endif; ?><small><?= e($m['original_name']) ?></small></label><?php endforeach; ?></div></aside>
    <?php if($isEdit && $attached): ?><section class="panel"><h2>Bu kayda bagli medya</h2><div class="media-grid"><?php foreach($attached as $m): ?><label class="media-card"><?php if($m['media_type']==='image'): ?><img src="../<?= e($m['relative_path']) ?>" alt=""><?php else: ?><div style="height:120px;display:grid;place-items:center;background:#090d11"><?= e(strtoupper($m['media_type'])) ?></div><?php endif; ?><small><?= e($m['original_name'] ?? $m['file_name']) ?></small><span class="check"><input type="checkbox" name="remove_media_ids[]" value="<?= (int)$m['media_id'] ?>"> Baglantiyi kaldir</span></label><?php endforeach; ?></div></section><?php endif; ?>
    <section class="panel"><h2>Baglantilar</h2><p>YouTube, Vimeo, SoundCloud, MP4/MP3, GitHub, calisan demo veya baska bir kaynak. Baslik bos kalirsa sistem kaynagi taniyip anlamli bir ad verir; desteklenen medya linkleri sitede player olarak gorunur.</p><div id="update-links" class="repeat-list"><?php foreach($links as $i=>$l): ?><div class="repeat-row"><select name="links[<?= $i ?>][type]"><?php foreach(['youtube','vimeo','soundcloud','instagram','github','website','download','external'] as $t): ?><option <?= $l['link_type']===$t?'selected':'' ?>><?= $t ?></option><?php endforeach; ?></select><input name="links[<?= $i ?>][title]" value="<?= e($l['title']) ?>"><input name="links[<?= $i ?>][url]" value="<?= e($l['url']) ?>"><button class="danger" type="button" data-repeat-remove>Sil</button></div><?php endforeach; ?></div><button class="secondary" type="button" data-repeat-add="#update-links" data-template="#update-link-template">+ Baglanti ekle</button></section></div>
    <template id="update-link-template"><div class="repeat-row"><select name="links[__INDEX__][type]"><option>youtube</option><option>vimeo</option><option>soundcloud</option><option>instagram</option><option>github</option><option>website</option><option>download</option><option>external</option></select><input name="links[__INDEX__][title]" placeholder="Baglanti basligi"><input name="links[__INDEX__][url]" placeholder="https://"><button class="danger" type="button" data-repeat-remove>Sil</button></div></template>
    <?php
}
