<?php
declare(strict_types=1);
function render_update_form(array $project,array $update=[],array $attached=[],array $links=[]): void
{
    $isEdit=!empty($update['id']); $media=project_media_admin((int)$project['id']);
    $v=fn(string $k,string $d='')=>e((string)($update[$k] ?? $d));
    ?>
    <div class="grid grid-2"><section class="panel"><h2>Çalışma kaydı</h2><div class="form-grid"><div class="field"><label>Çalışmanın tarihi</label><input type="date" name="work_date" value="<?= $v('work_date',date('Y-m-d')) ?>"></div><div class="field"><label>Görünen tarih / etiket</label><input name="display_label" value="<?= $v('display_label') ?>" placeholder="Boşsa tarihten oluşur"></div><div class="field full"><label>Başlık</label><input name="title" value="<?= $v('title') ?>" required></div><div class="field full"><label>Kısa özet</label><textarea name="summary"><?= $v('summary') ?></textarea></div><div class="field full"><label>Ne denedim?</label><textarea name="tried"><?= $v('tried') ?></textarea></div><div class="field full"><label>Ne çalışmadı?</label><textarea name="failed"><?= $v('failed') ?></textarea></div><div class="field full"><label>Hangi kararı verdim?</label><textarea name="decision"><?= $v('decision') ?></textarea></div><div class="field full"><label>Sırada ne var?</label><textarea name="next_step"><?= $v('next_step') ?></textarea></div><div class="field"><label>Faz / dönem</label><input name="phase" value="<?= $v('phase','Genel') ?>" placeholder="Başlangıç, Denemeler, Yön değişikliği"></div><div class="field"><label>Slug</label><input name="slug" value="<?= $v('slug') ?>" placeholder="Boşsa başlıktan oluşur"></div></div></section>
    <aside class="panel"><h2>Yayın kararı</h2><div class="field"><label>Durum</label><select name="status"><option value="draft" <?= ($update['status']??'draft')==='draft'?'selected':'' ?>>Taslak</option><option value="published" <?= ($update['status']??'')==='published'?'selected':'' ?>>Yayımla</option></select></div><div class="field"><label>Görünürlük</label><select name="visibility"><option value="private" <?= ($update['visibility']??'public')==='private'?'selected':'' ?>>Gizli</option><option value="unlisted" <?= ($update['visibility']??'')==='unlisted'?'selected':'' ?>>Bağlantıya sahip olanlar</option><option value="public" <?= ($update['visibility']??'public')==='public'?'selected':'' ?>>Herkese açık</option></select></div><div class="field"><label>Sıra</label><input type="number" step="0.1" name="sort_order" value="<?= $v('sort_order','999') ?>"></div><div class="check-row"><label class="check"><input type="checkbox" name="is_milestone" <?= !empty($update['is_milestone'])?'checked':'' ?>> Dönüm noktası</label><label class="check"><input type="checkbox" name="show_in_recent" <?= !isset($update['show_in_recent'])||$update['show_in_recent']?'checked':'' ?>> Son hareketlerde göster</label></div><p class="help">Kayıt her gün zorunlu değil. Küçük denemeleri ham günlükte tutabilir, yalnızca önemli kararları dönüm noktası yapabilirsin.</p></aside>
    <section class="panel"><h2>Yeni medya yükle</h2><div class="field"><label>Görsel, video, ses veya PDF</label><input type="file" name="media_files[]" multiple accept="image/jpeg,image/png,image/webp,image/gif,video/mp4,video/webm,audio/mpeg,audio/wav,audio/ogg,application/pdf"><small>Bir kayda birden fazla dosya eklenebilir. Büyük videolarda YouTube bağlantısı daha hafif olur.</small></div></section>
    <aside class="panel"><h2>Mevcut medyadan seç</h2><div class="media-grid"><?php foreach($media as $m): ?><label class="media-card"><input type="checkbox" name="existing_media_ids[]" value="<?= (int)$m['id'] ?>"><?php if($m['media_type']==='image'): ?><img src="../public/<?= e($m['relative_path']) ?>" alt=""><?php else: ?><div style="height:120px;display:grid;place-items:center;background:#090d11"><?= e(strtoupper($m['media_type'])) ?></div><?php endif; ?><small><?= e($m['original_name']) ?></small></label><?php endforeach; ?></div></aside>
    <?php if($isEdit && $attached): ?><section class="panel"><h2>Bu kayda bağlı medya</h2><div class="media-grid"><?php foreach($attached as $m): ?><label class="media-card"><?php if($m['media_type']==='image'): ?><img src="../public/<?= e($m['relative_path']) ?>" alt=""><?php else: ?><div style="height:120px;display:grid;place-items:center;background:#090d11"><?= e(strtoupper($m['media_type'])) ?></div><?php endif; ?><small><?= e($m['original_name'] ?? $m['file_name']) ?></small><span class="check"><input type="checkbox" name="remove_media_ids[]" value="<?= (int)$m['media_id'] ?>"> Bağlantıyı kaldır</span></label><?php endforeach; ?></div></section><?php endif; ?>
    <section class="panel"><h2>Bağlantılar</h2><p>YouTube, Instagram, GitHub, çalışan demo veya başka bir kaynak. Sınır yok.</p><div id="update-links" class="repeat-list"><?php foreach($links as $i=>$l): ?><div class="repeat-row"><select name="links[<?= $i ?>][type]"><?php foreach(['youtube','instagram','github','website','download','external'] as $t): ?><option <?= $l['link_type']===$t?'selected':'' ?>><?= $t ?></option><?php endforeach; ?></select><input name="links[<?= $i ?>][title]" value="<?= e($l['title']) ?>"><input name="links[<?= $i ?>][url]" value="<?= e($l['url']) ?>"><button class="danger" type="button" data-repeat-remove>Sil</button></div><?php endforeach; ?></div><button class="secondary" type="button" data-repeat-add="#update-links" data-template="#update-link-template">+ Bağlantı ekle</button></section></div>
    <template id="update-link-template"><div class="repeat-row"><select name="links[__INDEX__][type]"><option>youtube</option><option>instagram</option><option>github</option><option>website</option><option>download</option><option>external</option></select><input name="links[__INDEX__][title]" placeholder="Bağlantı başlığı"><input name="links[__INDEX__][url]" placeholder="https://"><button class="danger" type="button" data-repeat-remove>Sil</button></div></template>
    <?php
}
