<?php
declare(strict_types=1);
require __DIR__ . '/_bootstrap.php'; admin_require_login();
$projectId=(int)($_GET['project_id'] ?? $_POST['project_id'] ?? 0);$project=null;
if($projectId){$st=db()->prepare('SELECT * FROM projects WHERE id=?');$st->execute([$projectId]);$project=$st->fetch();}
$error='';
if(is_post()){
 verify_csrf();$action=(string)($_POST['action'] ?? 'upload');
 try{
  if($action==='upload'){if(!$project)throw new RuntimeException('Önce proje seçin.');$ids=save_uploaded_files($projectId,$project['slug']);flash('success',count($ids).' medya dosyası yüklendi.');redirect('media.php?project_id='.$projectId);}
  if($action==='metadata'){$id=(int)$_POST['media_id'];$st=db()->prepare('UPDATE media SET title=?,alt_text=?,caption=? WHERE id=?');$st->execute([trim(old('title')),trim(old('alt_text')),trim(old('caption')),$id]);flash('success','Medya bilgileri güncellendi.');redirect('media.php?project_id='.$projectId);}
  if($action==='delete'){$id=(int)$_POST['media_id'];$use=(int)db()->query('SELECT (SELECT COUNT(*) FROM update_media WHERE media_id=' . $id . ')+(SELECT COUNT(*) FROM story_section_media WHERE media_id=' . $id . ')+(SELECT COUNT(*) FROM story_sections WHERE media_id=' . $id . ')+(SELECT COUNT(*) FROM story_section_items WHERE media_id=' . $id . ')')->fetchColumn();if($use>0)throw new RuntimeException('Bu medya '.$use.' yerde kullanılıyor. Önce ilişkileri kaldırın.');db()->prepare('UPDATE media SET deleted_at=CURRENT_TIMESTAMP WHERE id=?')->execute([$id]);flash('success','Medya çöp kutusuna taşındı.');redirect('media.php?project_id='.$projectId);}
 }catch(Throwable $e){$error=$e->getMessage();}
}
$projects=admin_projects();$media=$projectId?project_media_admin($projectId):MediaRepository::latestAdmin(100);
admin_head('Medya kütüphanesi'); ?>
<div class="page-head"><div><p class="eyebrow">MEDYA KÜTÜPHANESİ</p><h1>Görsel, video, ses ve dosyalar</h1><p>Dosyalar diskte, ilişkileri ve açıklamaları SQLite içinde tutulur.</p></div></div><?php if($error): ?><div class="flash flash-error"><?= e($error) ?></div><?php endif; ?>
<form class="panel" method="get"><div class="form-grid"><div class="field"><label>Projeye göre filtrele</label><select name="project_id"><option value="">Son 100 medya</option><?php foreach($projects as $p): ?><option value="<?= (int)$p['id'] ?>" <?= $projectId===(int)$p['id']?'selected':'' ?>><?= e($p['title']) ?></option><?php endforeach; ?></select></div><div class="form-actions"><button type="submit">Göster</button></div></div></form>
<?php if($project): ?><form class="panel" method="post" enctype="multipart/form-data" style="margin-top:18px"><?= csrf_field() ?><input type="hidden" name="project_id" value="<?= $projectId ?>"><input type="hidden" name="action" value="upload"><h2><?= e($project['title']) ?> için yükle</h2><div class="field"><input type="file" name="media_files[]" multiple required></div><div class="form-actions"><button class="accent" type="submit">Dosyaları yükle</button></div></form><?php endif; ?>
<div class="media-grid" style="margin-top:24px"><?php foreach($media as $m): ?><article class="media-card"><?php if($m['media_type']==='image'): ?><img src="../public/<?= e($m['relative_path']) ?>" alt="<?= e($m['alt_text']) ?>"><?php elseif($m['media_type']==='video'): ?><video controls preload="metadata"><source src="../public/<?= e($m['relative_path']) ?>"></video><?php else: ?><div style="height:120px;display:grid;place-items:center;background:#090d11"><?= e(strtoupper($m['media_type'])) ?></div><?php endif; ?><small><?= e($m['original_name']) ?></small><form method="post"><?= csrf_field() ?><input type="hidden" name="project_id" value="<?= (int)$m['project_id'] ?>"><input type="hidden" name="media_id" value="<?= (int)$m['id'] ?>"><div class="field"><input name="title" value="<?= e($m['title']) ?>" placeholder="Başlık"></div><div class="field"><input name="alt_text" value="<?= e($m['alt_text']) ?>" placeholder="Alt metin"></div><div class="field"><textarea name="caption" placeholder="Açıklama"><?= e($m['caption']) ?></textarea></div><div class="form-actions"><button class="secondary" name="action" value="metadata">Kaydet</button><button class="danger" name="action" value="delete" data-confirm="Medya silinsin mi?">Sil</button></div></form></article><?php endforeach; ?></div>
<?php admin_foot(); ?>
