<?php
declare(strict_types=1);
require __DIR__ . '/_bootstrap.php'; admin_require_login();
$id=(int)($_GET['id'] ?? $_POST['id'] ?? 0); $project=null;
$st=db()->prepare("SELECT p.*,c.title category_title,m.relative_path cover_path,s.id story_id,s.status story_status,s.visibility story_visibility,s.published_at story_published_at
 FROM projects p LEFT JOIN categories c ON c.id=p.category_id LEFT JOIN media m ON m.id=p.cover_media_id LEFT JOIN stories s ON s.project_id=p.id AND s.deleted_at IS NULL WHERE p.id=?"); $st->execute([$id]); $project=$st->fetch();
if(!$project){http_response_code(404);exit('Proje bulunamadı.');}
$cats=categories(false); $media=project_media_admin($id); $updates=project_updates($id,false); $links=owner_links('project',$id); $error='';
if(is_post()){
    verify_csrf(); $action=(string)($_POST['action'] ?? 'save');
    try{
        if($action==='delete'){soft_delete_project($id);admin_audit('trash','project',$id);flash('success','Proje çöp kutusuna taşındı.');redirect('index.php');}
        if($action==='restore'){db()->prepare('UPDATE projects SET deleted_at=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=?')->execute([$id]);flash('success','Proje geri yüklendi.');redirect('project-edit.php?id='.$id);}
        if($action==='permanent_delete'){
            $slug=$project['slug']; db()->prepare('DELETE FROM projects WHERE id=?')->execute([$id]); admin_audit('permanent_delete','project',$id,$slug); flash('success','Proje kalıcı silindi. Medya dosyaları diskte güvenlik için bırakıldı.'); redirect('index.php?filter=trash');
        }
        db()->beginTransaction();
        $title=trim(old('title')); $slug=safe_slug(old('slug')); if($title===''||$slug==='') throw new RuntimeException('Başlık ve slug gerekli.');
        $workshopStatus=(string)($_POST['workshop_status'] ?? 'none');
        $showHome=checkbox('show_on_home'); $showArchive=checkbox('show_in_archive'); $homeSection=(string)($_POST['home_section'] ?? 'none');
        $normalized=admin_normalize_project_publication((bool)$showHome,$homeSection,(bool)$showArchive,(bool)checkbox('show_in_widget'),$workshopStatus);
        $showHome=(bool)$normalized['show_home']; $homeSection=(string)$normalized['home_section']; $showArchive=(bool)$normalized['show_archive']; $showWidget=(bool)$normalized['show_widget']; $workshopStatus=(string)$normalized['workshop_status'];
        $sortOrder=admin_resolve_project_sort_order((string)($_POST['sort_order'] ?? ''),$showHome,$homeSection,$showArchive);
        $st=db()->prepare("UPDATE projects SET slug=?,title=?,question=?,summary=?,category_id=?,status=?,status_label=?,type_label=?,visibility=?,workshop_status=?,workshop_question=?,closing_state=?,closing_note=?,started_at=?,ended_at=?,show_on_home=?,show_in_archive=?,show_in_widget=?,is_pinned=?,home_section=?,sort_order=?,updated_at=CURRENT_TIMESTAMP WHERE id=?");
        $st->execute([$slug,$title,trim(old('question')),trim(old('summary')),(int)($_POST['category_id'] ?? 0)?:null,(string)($_POST['status'] ?? 'draft'),trim(old('status_label')) ?: 'Kayıt',trim(old('type_label')) ?: 'Proje',(string)($_POST['visibility'] ?? 'private'),$workshopStatus,trim(old('workshop_question')),old('closing_state')?:null,trim(old('closing_note')),old('started_at')?:null,old('ended_at')?:null,$showHome?1:0,$showArchive?1:0,$showWidget?1:0,checkbox('is_pinned')?1:0,$homeSection,$sortOrder,$id]);
        if(checkbox('is_pinned')) db()->prepare('UPDATE projects SET is_pinned=0 WHERE id<>?')->execute([$id]);
        // tags
        db()->prepare('DELETE FROM project_tags WHERE project_id=?')->execute([$id]);
        foreach(array_filter(array_map('trim',explode(',',old('tags')))) as $tag){$ts=safe_slug($tag) ?: substr(sha1($tag),0,8);db()->prepare('INSERT OR IGNORE INTO tags(name,slug) VALUES (?,?)')->execute([$tag,$ts]);$tid=(int)db()->query("SELECT id FROM tags WHERE name=".db()->quote($tag))->fetchColumn();db()->prepare('INSERT OR IGNORE INTO project_tags(project_id,tag_id) VALUES (?,?)')->execute([$id,$tid]);}
        // cover existing/new
        $new=save_uploaded_files($id,$slug,'cover_upload'); $coverId=$new[0] ?? (int)($_POST['cover_media_id'] ?? 0); if($coverId) db()->prepare('UPDATE projects SET cover_media_id=? WHERE id=?')->execute([$coverId,$id]);
        // project links replace
        LinkRepository::replaceForOwner('project', $id, is_array($_POST['links'] ?? null) ? $_POST['links'] : [], fn($title,$type,$url) => admin_link_title((string)$title, (string)$type, (string)$url));
        db()->commit(); admin_audit('update','project',$id,$title);
        flash('success','Proje kaydedildi.');
        foreach($normalized['warnings'] as $warning) flash('warning',$warning);
        if($story && in_array($workshopStatus,['open','paused'],true)){
            flash('warning','Bu projede mevcut bir hikaye var. Atolye yeniden acildiginda eski hikaye referans olarak kalir; yeni isler ayri Atolye kaydi olarak eklenir.');
        }
        if(!$showWidget && in_array($workshopStatus,['open','paused'],true)){
            $hasUpdates=project_has_updates($id);
            flash('warning',$hasUpdates ? 'Atolye penceresi kapatildi. Projenin Atolye sayfasi ve mevcut kayitlari duruyor; tamamen kapatmak istersen Atolye durumunu Kapandi veya Yok yap.' : 'Atolye penceresi kapatildi. Bu projede henuz Atolye kaydi yok; Atolye durumunu da Yok yaparsan public Atolye sayfasi kapanir.');
        }
        foreach(admin_project_sort_conflicts($id,$sortOrder,$showHome,$homeSection,$showArchive) as $warning) flash('warning',$warning);
        redirect('project-edit.php?id='.$id);
    }catch(Throwable $e){if(db()->inTransaction())db()->rollBack();$error=admin_error_message($e,'admin.project_edit');}
}
$tags=implode(', ',project_tags($id)); $story=story_by_project($id,true); $sortWarnings=admin_project_sort_conflicts($id,(float)$project['sort_order'],(bool)$project['show_on_home'],(string)$project['home_section'],(bool)$project['show_in_archive']); $projectWidgetCanBeChecked=VisibilityService::workshopStatusAllowsWidget((string)($project['workshop_status'] ?? 'none')); $projectWidgetWasInconsistent=!empty($project['show_in_widget']) && !$projectWidgetCanBeChecked; admin_head('Projeyi yönet'); ?>
<div class="page-head"><div><p class="eyebrow">PROJE #<?= $id ?></p><h1><?= e($project['title']) ?></h1><p>Yayın, görünürlük ve sıra birbirinden bağımsızdır. İçeriği silmeden gizleyebilirsin.</p></div><div class="form-actions"><a class="button secondary" href="update-new.php?project_id=<?= $id ?>">+ Atölye kaydı</a><a class="button secondary" href="story-builder.php?project_id=<?= $id ?>">Atölyeden hikâye</a><?php if($project['story_id']): ?><a class="button secondary" href="story-edit.php?project_id=<?= $id ?>">Hikâyeyi düzenle</a><?php endif; ?></div></div><?php if($error): ?><div class="flash flash-error"><?= e($error) ?></div><?php endif; ?><?php foreach($sortWarnings as $warning): ?><div class="flash flash-warning"><?= e($warning) ?></div><?php endforeach; ?><?php admin_render_visibility_summary($project,$story); ?><?php if($story && in_array((string)$project['workshop_status'],['open','paused'],true)): ?><section class="panel"><h2>Mevcut hikaye referansi</h2><p class="help">Bu proje yeniden Atolye durumunda. Eski hikaye bolumleri Atolye kaydina kopyalanmaz; public Atolye ekraninda duzenlenmis hikaye referansi olarak gorunur. Yeni isler ayri Atolye kayitlari olarak eklenir.</p></section><?php endif; ?>
<form method="post" enctype="multipart/form-data"><input type="hidden" name="id" value="<?= $id ?>"><?= csrf_field() ?><div class="grid grid-2"><section class="panel"><h2>Kimlik ve anlatı</h2><div class="form-grid"><div class="field"><label>Proje adı</label><input name="title" value="<?= e($project['title']) ?>" required><small>Kartlarda küçük kimlik satırı olarak görünür.</small></div><div class="field"><label>Slug</label><input name="slug" value="<?= e($project['slug']) ?>" required></div><div class="field full"><label>Merak sorusu</label><input name="question" value="<?= e($project['question']) ?>"></div><div class="field full"><label>Özet</label><textarea name="summary"><?= e($project['summary']) ?></textarea></div><div class="field"><label>Kategori</label><select name="category_id"><option value="">Seçin</option><?php foreach($cats as $c): ?><option value="<?= (int)$c['id'] ?>" <?= (int)$project['category_id']===(int)$c['id']?'selected':'' ?>><?= e($c['title']) ?></option><?php endforeach; ?></select></div><div class="field"><label>Etiketler</label><input name="tags" value="<?= e($tags) ?>" placeholder="Python, Yapay zekâ, Krita"></div><div class="field"><label>Durum kodu</label><select name="status"><?php foreach(['fikir','suruyor','calisiyor','denendi','tamamlandi','yarim','not','arsiv'] as $v): ?><option value="<?= $v ?>" <?= $project['status']===$v?'selected':'' ?>><?= $v ?></option><?php endforeach; ?></select></div><div class="field"><label>Görünen durum</label><input name="status_label" value="<?= e($project['status_label']) ?>"></div><div class="field"><label>İçerik türü</label><input name="type_label" value="<?= e($project['type_label']) ?>"><small>Varsa proje adının yanında kısa tip olarak gösterilir.</small></div></div></section>
<aside class="panel"><h2>Yayın ve görünürlük</h2><div class="field"><label>Görünürlük</label><select name="visibility"><option value="private" <?= $project['visibility']==='private'?'selected':'' ?>>Gizli</option><option value="unlisted" <?= $project['visibility']==='unlisted'?'selected':'' ?>>Bağlantıya sahip olanlar</option><option value="public" <?= $project['visibility']==='public'?'selected':'' ?>>Herkese açık</option></select></div><div class="field"><label>Ana sayfadaki yeri</label><select name="home_section"><option value="none" <?= $project['home_section']==='none'?'selected':'' ?>>Kapalı</option><option value="focus" <?= $project['home_section']==='focus'?'selected':'' ?>>Öne çıkan büyük kart</option><option value="trace" <?= $project['home_section']==='trace'?'selected':'' ?>>Alt şerit / küçük kayıt</option></select></div><div class="field"><label>Sıra</label><input type="number" step="0.1" name="sort_order" value="<?= e((string)$project['sort_order']) ?>" placeholder="Boşsa otomatik"></div><div class="check-row"><label class="check"><input type="checkbox" name="show_on_home" <?= $project['show_on_home']?'checked':'' ?>> Ana sayfada göster</label><label class="check"><input type="checkbox" name="show_in_archive" <?= $project['show_in_archive']?'checked':'' ?>> Hikâyeler sayfasında göster</label><label class="check"><input type="checkbox" name="show_in_widget" <?= $project['show_in_widget'] && $projectWidgetCanBeChecked?'checked':'' ?>> Atölye penceresinde göster</label><label class="check"><input type="checkbox" name="is_pinned" <?= $project['is_pinned']?'checked':'' ?>> Sabitle</label></div><p class="help">Ana sayfa ve Hikâyeler sayfası için hikâyenin ayrıca Yayımlandı ve Herkese açık olması gerekir. Sıra boş bırakılırsa sistem aynı alanda sonraki uygun sayıyı verir.</p><p class="help">Atölye penceresinde görünmesi için proje public olmalı, Atölye durumu Açık veya Beklemede olmalı ve bu seçenek işaretli olmalı.</p></aside>
<section class="panel"><h2>Atölye yaşam döngüsü</h2><div class="form-grid"><div class="field"><label>Atölye durumu</label><select name="workshop_status"><option value="none" <?= $project['workshop_status']==='none'?'selected':'' ?>>Yok</option><option value="open" <?= $project['workshop_status']==='open'?'selected':'' ?>>Açık</option><option value="paused" <?= $project['workshop_status']==='paused'?'selected':'' ?>>Beklemede</option><option value="closed" <?= $project['workshop_status']==='closed'?'selected':'' ?>>Kapandı</option></select></div><div class="field"><label>Atölye sorusu</label><input name="workshop_question" value="<?= e($project['workshop_question']) ?>"></div><div class="field"><label>Başlangıç tarihi</label><input type="date" name="started_at" value="<?= e((string)$project['started_at']) ?>"></div><div class="field"><label>Bitiş tarihi</label><input type="date" name="ended_at" value="<?= e((string)$project['ended_at']) ?>"></div><div class="field"><label>Kapanış kararı</label><select name="closing_state"><option value="">Seçin</option><?php foreach(['Bu hâliyle bitti','Yarım bıraktım','Beklemeye aldım','Başka projeye dönüştü'] as $v): ?><option <?= $project['closing_state']===$v?'selected':'' ?>><?= e($v) ?></option><?php endforeach; ?></select></div><div class="field full"><label>Kapanış notu</label><textarea name="closing_note"><?= e($project['closing_note']) ?></textarea></div></div></section>
<aside class="panel"><h2>Kapak ve medya</h2><?php if($project['cover_path']): ?><img style="width:100%;max-height:220px;object-fit:cover;border-radius:8px" src="../<?= e($project['cover_path']) ?>" alt=""><?php endif; ?><div class="field"><label>Yeni kapak yükle</label><input type="file" name="cover_upload[]" accept="image/jpeg,image/png,image/webp,image/gif"></div><div class="field"><label>Mevcut medyadan kapak</label><select name="cover_media_id"><option value="">Değiştirme</option><?php foreach($media as $m): if($m['media_type']!=='image')continue; ?><option value="<?= (int)$m['id'] ?>" <?= (int)$project['cover_media_id']===(int)$m['id']?'selected':'' ?>><?= e($m['original_name']) ?></option><?php endforeach; ?></select></div><a class="button secondary" href="media.php?project_id=<?= $id ?>">Medya kütüphanesi</a></aside>
<section class="panel"><h2>Proje bağlantıları</h2><p class="help">Başlık boşsa sistem kaynağı tanıyıp anlamlı bir ad verir.</p><div id="project-links" class="repeat-list"><?php foreach($links as $i=>$l): ?><div class="repeat-row"><select name="links[<?= $i ?>][type]"><?php foreach(['website','youtube','vimeo','soundcloud','instagram','github','download','external'] as $t): ?><option <?= $l['link_type']===$t?'selected':'' ?>><?= $t ?></option><?php endforeach; ?></select><input name="links[<?= $i ?>][title]" value="<?= e($l['title']) ?>" placeholder="Başlık"><input name="links[<?= $i ?>][url]" value="<?= e($l['url']) ?>" placeholder="https://"><button class="danger" type="button" data-repeat-remove>Sil</button></div><?php endforeach; ?></div><button class="secondary" type="button" data-repeat-add="#project-links" data-template="#link-template">+ Bağlantı ekle</button></section>
<aside class="panel"><h2>Kayıtlar</h2><p><?= count($updates) ?> Atölye kaydı var.</p><a class="button secondary" href="update-new.php?project_id=<?= $id ?>">Yeni kayıt</a><?php if($updates): ?><div class="list" style="margin-top:14px"><?php foreach(array_slice(array_reverse($updates),0,5) as $u): ?><a class="list-row" href="update-edit.php?id=<?= (int)$u['id'] ?>"><span><?= e($u['date_label']) ?></span><strong><?= e($u['title']) ?></strong><small><?= $u['status']==='published'?'Yayında':'Taslak' ?></small></a><?php endforeach; ?></div><?php endif; ?></aside></div>
<div class="form-actions"><button class="accent" type="submit" name="action" value="save">Projeyi kaydet</button><a class="button secondary" href="index.php">Listeye dön</a><?php if(!$project['deleted_at']): ?><button class="danger" type="submit" name="action" value="delete" data-confirm="Proje çöp kutusuna taşınsın mı?">Çöp kutusuna taşı</button><?php else: ?><button type="submit" name="action" value="restore">Geri yükle</button><button class="danger" type="submit" name="action" value="permanent_delete" data-confirm="Bu işlem geri alınamaz. Kalıcı silinsin mi?">Kalıcı sil</button><?php endif; ?></div></form>
<template id="link-template"><div class="repeat-row"><select name="links[__INDEX__][type]"><option>website</option><option>youtube</option><option>vimeo</option><option>soundcloud</option><option>instagram</option><option>github</option><option>download</option><option>external</option></select><input name="links[__INDEX__][title]" placeholder="Başlık"><input name="links[__INDEX__][url]" placeholder="https://"><button class="danger" type="button" data-repeat-remove>Sil</button></div></template>

<?php admin_foot(); ?>
