<?php
declare(strict_types=1);
require __DIR__ . '/_bootstrap.php'; admin_require_login();
$projectId=(int)($_GET['project_id'] ?? $_POST['project_id'] ?? 0);
$st=db()->prepare('SELECT * FROM projects WHERE id=?');$st->execute([$projectId]);$project=$st->fetch();if(!$project){http_response_code(404);exit('Proje yok.');}
$story=story_by_project($projectId,true);
if(!$story){flash('error','Önce hikâye taslağı oluşturmalısın.');redirect('story-builder.php?project_id='.$projectId);}
$error='';
if(is_post()){
  verify_csrf();$action=(string)($_POST['action'] ?? 'save');
  try{
    if(str_starts_with($action,'move_')){
      [, $dir,$sid]=explode('_',$action);$sid=(int)$sid;$sections=story_sections((int)$story['id']);$ids=array_column($sections,'id');$pos=array_search($sid,$ids,true);if($pos!==false){$target=$dir==='up'?$pos-1:$pos+1;if(isset($ids[$target])){$a=$sections[$pos];$b=$sections[$target];db()->beginTransaction();db()->prepare('UPDATE story_sections SET sort_order=? WHERE id=?')->execute([$b['sort_order'],$a['id']]);db()->prepare('UPDATE story_sections SET sort_order=? WHERE id=?')->execute([$a['sort_order'],$b['id']]);db()->commit();}}redirect('story-edit.php?project_id='.$projectId);
    }
    if(str_starts_with($action,'delete_')){$sid=(int)substr($action,7);db()->prepare('UPDATE story_sections SET deleted_at=CURRENT_TIMESTAMP WHERE id=? AND story_id=?')->execute([$sid,$story['id']]);flash('success','Bölüm silindi.');redirect('story-edit.php?project_id='.$projectId);}
    $status=(string)($_POST['status'] ?? 'draft');
    $st=db()->prepare("UPDATE stories SET title=?,question=?,summary=?,reading_time=?,status=?,visibility=?,show_on_home=?,show_in_archive=?,is_pinned=?,sort_order=?,published_at=CASE WHEN ?='published' AND published_at IS NULL THEN CURRENT_TIMESTAMP ELSE published_at END,updated_at=CURRENT_TIMESTAMP WHERE id=?");
    $st->execute([trim(old('title')),trim(old('question')),trim(old('summary')),trim(old('reading_time')),$status,(string)($_POST['visibility'] ?? 'public'),checkbox('show_on_home'),checkbox('show_in_archive'),checkbox('is_pinned'),(float)($_POST['sort_order'] ?? 999),$status,$story['id']]);
    admin_audit('update','story',(int)$story['id']);flash('success','Hikâye ayarları kaydedildi.');redirect('story-edit.php?project_id='.$projectId);
  }catch(Throwable $e){if(db()->inTransaction())db()->rollBack();$error=$e->getMessage();}
}
$story=story_by_project($projectId,true);$sections=story_sections((int)$story['id']);admin_head('Hikâyeyi düzenle'); ?>
<div class="page-head"><div><p class="eyebrow"><?= e($project['title']) ?></p><h1>Hikâyeyi düzenle</h1><p>JSON yok. Bölümleri form ekranlarıyla ekle, sırala, düzenle veya gizle.</p></div><a class="button secondary" href="../public/hikaye.php?slug=<?= e(rawurlencode($project['slug'])) ?>" target="_blank">Ön izle</a></div><?php if($error): ?><div class="flash flash-error"><?= e($error) ?></div><?php endif; ?>
<?php admin_render_visibility_summary($project,$story); ?>
<form class="panel" method="post"><input type="hidden" name="project_id" value="<?= $projectId ?>"><?= csrf_field() ?><div class="form-grid"><div class="field"><label>Hikâye başlığı</label><input name="title" value="<?= e($story['title']) ?>"><small>Büyük görünen anlatı başlığıdır; proje adı ayrı gösterilir.</small></div><div class="field"><label>Okuma süresi</label><input name="reading_time" value="<?= e($story['reading_time']) ?>" placeholder="3–6 dk"></div><div class="field full"><label>Merak sorusu</label><input name="question" value="<?= e($story['question']) ?>"><small>Doluysa kartlarda ana büyük başlık olarak bu soru kullanılır.</small></div><div class="field full"><label>Özet</label><textarea name="summary"><?= e($story['summary']) ?></textarea></div><div class="field"><label>Durum</label><select name="status"><option value="draft" <?= $story['status']==='draft'?'selected':'' ?>>Taslak</option><option value="published" <?= $story['status']==='published'?'selected':'' ?>>Yayımlandı</option><option value="archived" <?= $story['status']==='archived'?'selected':'' ?>>Arşivde</option></select></div><div class="field"><label>Görünürlük</label><select name="visibility"><option value="private" <?= $story['visibility']==='private'?'selected':'' ?>>Gizli</option><option value="unlisted" <?= $story['visibility']==='unlisted'?'selected':'' ?>>Bağlantıya sahip olanlar</option><option value="public" <?= $story['visibility']==='public'?'selected':'' ?>>Herkese açık</option></select></div><div class="field"><label>Sıra (eski story alanı)</label><input type="number" step="0.1" name="sort_order" value="<?= e((string)$story['sort_order']) ?>"></div><div class="field full check-row"><label class="check"><input type="checkbox" name="show_on_home" <?= $story['show_on_home']?'checked':'' ?>> Story ana sayfa bayrağı</label><label class="check"><input type="checkbox" name="show_in_archive" <?= $story['show_in_archive']?'checked':'' ?>> Story arşiv bayrağı</label><label class="check"><input type="checkbox" name="is_pinned" <?= $story['is_pinned']?'checked':'' ?>> Sabitle</label></div><p class="help">Public ana sayfa ve Hikâyeler sayfasındaki yerleşimi Projeyi yönet ekranındaki “Ana sayfada göster”, “Hikâyeler sayfasında göster” ve “Ana sayfadaki yeri” alanları belirler. Bu story bayrakları eski uyumluluk için tutulur.</p></div><div class="form-actions"><button class="accent" type="submit" name="action" value="save">Ayarları kaydet</button></div></form>
<div class="page-head" style="margin-top:45px"><div><p class="eyebrow">HİKÂYE BÖLÜMLERİ</p><h2>Mevcut kayıtlar</h2></div><a class="button accent" href="section-edit.php?story_id=<?= (int)$story['id'] ?>">+ Yeni bölüm</a></div>
<?php if(!$sections): ?><div class="empty">Henüz hikâye bölümü yok.</div><?php else: ?><form method="post"><input type="hidden" name="project_id" value="<?= $projectId ?>"><?= csrf_field() ?><div class="list"><?php foreach($sections as $i=>$s): ?><article class="section-card"><span class="num"><?= str_pad((string)($i+1),2,'0',STR_PAD_LEFT) ?></span><div><small><?= e(strtoupper($s['type'])) ?> · <?= e($s['layout']) ?></small><h3><?= e($s['title'] ?: 'Başlıksız bölüm') ?></h3><p><?= e(mb_strimwidth(strip_tags($s['body_text'] ?: $s['intro_text']),0,150,'…','UTF-8')) ?></p></div><div class="card-actions"><a class="button secondary" href="section-edit.php?id=<?= (int)$s['id'] ?>">Düzenle</a><button class="secondary" name="action" value="move_up_<?= (int)$s['id'] ?>">↑</button><button class="secondary" name="action" value="move_down_<?= (int)$s['id'] ?>">↓</button><button class="danger" name="action" value="delete_<?= (int)$s['id'] ?>" data-confirm="Bölüm silinsin mi?">Sil</button></div></article><?php endforeach; ?></div></form><?php endif; ?>
<?php admin_foot(); ?>
