<?php
declare(strict_types=1);
require __DIR__ . '/../app/bootstrap.php';
$slug=safe_slug((string)($_GET['slug'] ?? '')); $project=project_by_slug($slug); $site=setting('site',[]);
$updates=$project ? project_updates((int)$project['id']) : []; $active=$updates ? end($updates) : null; if($updates) reset($updates);
$milestones=array_values(array_filter($updates,fn($u)=>(int)$u['is_milestone']===1)); if(!$milestones && $updates) $milestones=$updates;
$story=$project ? story_by_project((int)$project['id']) : null;
if(!$project || (!in_array($project['workshop_status'],['open','paused','closed'],true) && !$updates)) http_response_code(404);
$grouped=[]; foreach($updates as $u) $grouped[$u['phase'] ?: 'Genel'][]=$u;
function first_stage_media(array $u): ?array { foreach($u['media'] ?? [] as $m) if(($m['media_type'] ?? '')==='image') return $m; return $u['media'][0] ?? null; }
?>
<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#0d1014"><meta name="description" content="<?= e($project['summary'] ?? 'Canlı atölye günlüğü') ?>"><title><?= e($project['title'] ?? 'Atölye') ?> | #FikrimVar</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,400;9..144,600&family=IBM+Plex+Mono:wght@400;500;600&family=Inter:wght@400;500;600&display=swap" rel="stylesheet"><link rel="stylesheet" href="assets/css/style.css"><script src="assets/js/app.js" defer></script></head><body class="atelier-page"><a class="skip-link" href="#atelier-main">İçeriğe geç</a><header class="inner-header inner-header--dark"><div class="shell inner-header-row"><a class="brand" href="index.php"><span class="brand-name">AHMET ÇETİN</span><span class="brand-mark">#FikrimVar</span></a><nav><a href="hikayeler.php">Bütün hikâyeler</a><?php if($story): ?><a href="hikaye.php?slug=<?= e(rawurlencode($slug)) ?>">Düzenlenmiş hikâye</a><?php endif; ?><a href="index.php">Ana sayfa</a></nav></div></header><main id="atelier-main">
<?php if(!$project): ?><section class="not-found"><div class="shell"><p class="eyebrow">404</p><h1>Atölye kaydı bulunamadı.</h1></div></section><?php else: ?>
<section class="atelier-hero"><div class="shell atelier-hero-grid"><div data-reveal><p class="eyebrow"><?= $project['workshop_status']==='closed'?'ATÖLYE KAPANDI':'CANLI ATÖLYE' ?> · <?= e($project['status_label']) ?></p><h1><?= e($project['title']) ?></h1></div><div data-reveal><p class="atelier-question"><?= e($project['workshop_question'] ?: $project['question']) ?></p><p><?= e($project['summary']) ?></p><div class="atelier-meta"><span><?= count($updates) ?> çalışma kaydı</span><span><?= count($milestones) ?> dönüm noktası</span><span>Kayıt her gün zorunlu değil</span></div></div></div></section>
<?php if($project['workshop_status']==='closed'): ?><section class="atelier-closed-note"><div class="shell"><p class="eyebrow">ATÖLYE KAPALI</p><h2><?= e($project['closing_state'] ?: 'Bu hâliyle bitti') ?></h2><p><?= e($project['closing_note']) ?></p><?php if($story): ?><a class="button button-rust" href="hikaye.php?slug=<?= e(rawurlencode($slug)) ?>">Hikâyeyi oku <?= icon('arrow') ?></a><?php endif; ?></div></section><?php endif; ?>
<?php if($active): $stage=first_stage_media($active); ?>
<section class="atelier-console" data-atelier-console><div class="atelier-stage-wrap"><div class="atelier-stage-sticky"><div class="atelier-live-label"><span></span> ATÖLYEDE ŞİMDİ</div><figure class="atelier-stage-media" data-atelier-stage><?php if($stage && ($stage['media_type'] ?? '')==='image'): ?><img src="<?= e(media_url($stage['relative_path'])) ?>" alt="<?= e($stage['alt_text'] ?? $project['title']) ?>" data-atelier-media><?php elseif($stage && ($stage['media_type'] ?? '')==='video'): ?><video controls preload="metadata"><source src="<?= e(media_url($stage['relative_path'])) ?>"></video><?php elseif($project['cover']!==''): ?><img src="<?= e($project['cover']) ?>" alt="<?= e($project['title']) ?>" data-atelier-media><?php endif; ?></figure><div class="atelier-stage-copy"><p data-atelier-day><?= e($active['date_label']) ?></p><h2 data-atelier-title><?= e($active['title']) ?></h2><p data-atelier-summary><?= e($active['summary']) ?></p><dl><div><dt>Denediğim</dt><dd data-atelier-tried><?= e($active['tried']) ?></dd></div><div><dt>Çalışmayan</dt><dd data-atelier-failed><?= e($active['failed']) ?></dd></div><div><dt>Kararım</dt><dd data-atelier-decision><?= e($active['decision']) ?></dd></div><div><dt>Sıradaki</dt><dd data-atelier-next><?= e($active['next_step']) ?></dd></div></dl><?php render_external_links($active['links']); ?></div></div></div>
<div class="atelier-log"><header><p class="eyebrow">DÖNÜM NOKTALARI</p><h2><?= count($updates) ?> kaydın içinden yönü değiştirenler.</h2><p>Ham günlük aşağıda saklı. Burada yalnızca projeyi başka bir yola sokan kararlar var.</p></header><?php foreach($milestones as $u): $sm=first_stage_media($u); ?><button class="atelier-log-entry <?= $u['id']===$active['id']?'is-active':'' ?>" id="update-<?= e($u['slug']) ?>" type="button" data-atelier-entry data-media="<?= e($sm?media_url($sm['relative_path']):$project['cover']) ?>" data-media-type="<?= e($sm['media_type'] ?? 'image') ?>" data-alt="<?= e($sm['alt_text'] ?? '') ?>" data-update-id="<?= e($u['slug']) ?>" data-day="<?= e($u['date_label']) ?>" data-title="<?= e($u['title']) ?>" data-summary="<?= e($u['summary']) ?>" data-tried="<?= e($u['tried']) ?>" data-failed="<?= e($u['failed']) ?>" data-decision="<?= e($u['decision']) ?>" data-next="<?= e($u['next_step']) ?>"><span><?= e($u['date_label']) ?></span><strong><?= e($u['title']) ?></strong><small><?= e($u['summary']) ?></small></button><?php endforeach; ?></div></section>
<section class="atelier-raw-log"><div class="shell"><header data-reveal><p class="eyebrow">HAM ÇALIŞMA GÜNLÜĞÜ</p><h2>Tüm kayıtlar, fazlara göre.</h2><p>Üç günde bir de olabilir, üç haftada bir de. Bu bölüm takvim zorunluluğu değil, hafıza alanı.</p></header><?php foreach($grouped as $phase=>$phaseUpdates): ?><details class="atelier-phase"><summary><strong><?= e($phase) ?></strong><span><?= count($phaseUpdates) ?> kayıt</span></summary><div class="atelier-phase-list"><?php foreach(array_reverse($phaseUpdates) as $u): ?><article id="ham-<?= e($u['slug']) ?>"><div><small><?= e($u['date_label']) ?></small><h3><?= e($u['title']) ?></h3><p><?= e($u['summary']) ?></p></div><?php render_media_items($u['media'],'atelier-entry-media'); ?><?php render_external_links($u['links']); ?></article><?php endforeach; ?></div></details><?php endforeach; ?></div></section>
<?php endif; ?>
<section class="atelier-rule"><div class="shell atelier-rule-grid" data-reveal><p class="eyebrow">ATÖLYENİN KAPANIŞ KURALI</p><h2>Bir projenin tamamlanması şart değil.</h2><p>Hedeflediğim yere geldiğimde, öğrenmek istediğimi öğrendiğimde veya artık devam etmek istemediğimde kapanır. Ham kayıtlar kalır; seçilen dönüm noktaları düzenlenmiş hikâyeye dönüşür.</p></div></section><section class="story-signature story-signature--dark"><div class="shell story-signature-grid" data-reveal><p class="eyebrow">#FikrimVar</p><blockquote>Kusursuz olmak değil; denemek, yanılmak, öğrenmek ve fikri hayata geçirmek.</blockquote><nav><a href="hikayeler.php">Bütün hikâyeler <?= icon('arrow') ?></a><a href="index.php">Ana sayfa <?= icon('arrow') ?></a></nav></div></section>
<?php endif; ?></main><footer class="site-footer site-footer--dark"><div class="shell footer-inner"><p>© <?= e((string)($site['year'] ?? date('Y'))) ?> Ahmet Çetin · #FikrimVar</p><a href="index.php">Ana sayfaya dön</a></div></footer></body></html>
